# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Test and restore Csharp code
      run: cd ./Csharp/tests && dotnet restore && dotnet build && dotnet test --no-build --verbosity normal
    - name: Test and restore Fsharp code
      run: cd ./Fsharp/tests && dotnet restore && dotnet build && dotnet test --no-build --verbosity normal
